### ISSUE TITLE
Negative KL loss

### ISSUE THREAD

**Issue by laplaceon** [sony/sqvae#1] opened 2022-07-18 19:06 UTC
Hello, I tried training a model with my audio dataset using the GaussianVectorQuantizer from the speech folder. I end up getting a negative kl loss, which gets worse (further from zero) with each epoch and a reconstruction loss which fails to improve after the 2nd epoch. I ran the MNIST training script and printed out the average kl and reconstruction losses to see if the kl loss was also negative, which it turned out to be. While the kl loss for MNIST was negative, it was approaching zero with each epoch. I also ran the training script for CelebA. This time, the distribution loss was positive as well as approaching zero with each epoch. Is this negative kl loss to be expected for some datasets, or is this indicative of an underlying issue with my model/training process?

**Comment by TakashiShibuyaSony** [comment] 2022-07-21 10:19
Thank you for having an interest in our work! And, I'm sorry for my late response.

I don't have a clear idea about the cause because I don't know the details about your entire code, but training stability definitely depends on a dataset. If you use the "gaussian_4" setting, I recommend you use the "gausssian_1" setting. "gausssian_1" is more stable than "gaussian_4".

**Comment by TakashiShibuyaSony** [comment] 2022-07-21 12:03
Thank you for having an interest in our work! And, I'm sorry for my late response.

We omitted the constant term of KLD in our code. So, a loss value is not a true KLD and might get negative. I'm sorry for the confusion.

On the other hand, I don't have a clear idea about why a reconstruction loss doesn't improve. I don't know the details about your entire code and setup, but training stability definitely depends on a dataset. If you use the "gaussian_4" setting, I recommend you use the "gausssian_1" setting. "gausssian_1" is more stable than "gaussian_4".

https://github.com/sony/sqvae/blob/dc88ab1a48f7596b3650e19de65e81b8f0498ee4/speech/model.py#L135-L140

**Comment by TakashiShibuyaSony** [comment] 2022-08-02 08:52
I've closed this issue. If you still have a question, feel free to ask.

**Closed as completed by TakashiShibuyaSony** 2022-08-02 08:52 UTC
